#ifndef __PLATFORM_OPTS_BT_H__
#define __PLATFORM_OPTS_BT_H__

/* Board About */
#define CONFIG_PLATFORM_8710C 1
#define CONFIG_ARM 1
#define CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC 72000000
#define CONFIG_HEAP_MEM_POOL_SIZE 0
#define CONFIG_CLOCK_CONTROL 1
#define CONFIG_USE_ZEPHYR_BT_STACK 1


/* OS About */
#define CONFIG_KERNEL_RTOS_FREERTOS 1
#define CONFIG_USE_STATIC_MEM 1
#define CONFIG_PRINTK 1
#define CONFIG_ASSERT 1
#define __LINUX_ERRNO_EXTENSIONS__
//#define CONFIG_ASSERT_NO_MSG_INFO 1
//#define CONFIG_OS_INTF_DEBUG 1


/* Dependence About */
#define CONFIG_TINYCRYPT 1
#ifdef CONFIG_TINYCRYPT
	#define CONFIG_TINYCRYPT_SHA256 1
	#define CONFIG_TINYCRYPT_SHA256_HMAC 1
	#define CONFIG_TINYCRYPT_SHA256_HMAC_PRNG 1
	#define CONFIG_TINYCRYPT_AES 1
	#define CONFIG_TINYCRYPT_AES_CMAC 1
#endif
//#define CONFIG_ATOMIC_OPERATIONS_BUILTIN 1
//#define CONFIG_ATOMIC_OPERATIONS_C 1
//#define CONFIG_NET_BUF_LOG 1
#define CONFIG_NET_BUF_WARN_ALLOC_INTERVAL 0
#define CONFIG_NET_BUF_USER_DATA_SIZE 4
#define CONFIG_NET_BUF_LOG_LEVEL 3


/* BT HCI About */
#define CONFIG_BT_HCI 1
#define CONFIG_BT_UART_ON_DEV_NAME "AmbeaZ2_BT_UART"
#define CONFIG_BT_HCI_ACL_FLOW_CONTROL 1
#define CONFIG_BT_HCI_VS_EXT 1
#define CONFIG_BT_HCI_VS 1
#define CONFIG_BT_HCI_MESH_EXT 1
#define CONFIG_BT_HCI_HOST 1
#define CONFIG_BT_HCI_BTSNOOP 1
#define CONFIG_BT_HCI_BTSNOOP_TASK 0
#define CONFIG_BT_HCI_CMD_COUNT 2
#define CONFIG_BT_HCI_TX_STACK_SIZE 512
#define CONFIG_BT_HCI_ECC_STACK_SIZE 1024
#define CONFIG_BT_WORK_Q_STACK_SIZE 1024
//#define CONFIG_BT_RECV_IS_RX_THREAD 1
#ifdef CONFIG_BT_RECV_IS_RX_THREAD
	#define CONFIG_BT_RX_STACK_SIZE 2048
#else
	#define CONFIG_BT_RX_STACK_SIZE 1024
#endif
#define CONFIG_BT_HCI_RX_STACK_SIZE 1024
#define CONFIG_BT_HCI_RX_PRIO 6
#define CONFIG_BT_HCI_TX_PRIO 5
#define CONFIG_BT_WORK_Q_PRIO 7
#define CONFIG_BT_RX_PRIO 7
#define CONFIG_BT_MESH_ADV_PRIO 6
#define CONFIG_BT_HCI_RESERVE 1


/* BT Stack About */
#define CONFIG_BT 1
#define CONFIG_BT_PERIPHERAL 1
#define CONFIG_BT_CENTRAL 1
#define CONFIG_BT_BROADCASTER 1
#define CONFIG_BT_LIM_ADV_TIMEOUT 60
#define CONFIG_BT_OBSERVER 1
#define CONFIG_BT_DIS 1
#define CONFIG_BT_DIS_MODEL "AmbeaZ2"
#define CONFIG_BT_DIS_MANUF "RealTek"
#define CONFIG_BT_DIS_PNP 1
#define CONFIG_BT_DIS_PNP_VID_SRC 1
#define CONFIG_BT_DIS_PNP_VID 0x0
#define CONFIG_BT_DIS_PNP_PID 0x0
#define CONFIG_BT_DIS_PNP_VER 0x1
#define CONFIG_BT_BAS 1
#define CONFIG_BT_HRS 1
#define CONFIG_BT_TPS 1
#define CONFIG_BT_CONN 1
#define CONFIG_BT_MAX_CONN 2
//#define CONFIG_BT_REMOTE_VERSION 1
#define CONFIG_BT_PHY_UPDATE 1
#define CONFIG_BT_DATA_LEN_UPDATE 1
#define CONFIG_BT_RPA 1
#if 0//ndef CONFIG_BT_ZEPHYR_HCI
#define CONFIG_BT_RX_BUF_LEN 76
#else
#define CONFIG_BT_RX_BUF_LEN 258
#endif
#define CONFIG_BT_BUF_ACL_RX_SIZE 255
#define CONFIG_BT_BUF_EVT_DISCARDABLE_COUNT 3
#define CONFIG_BT_DRIVER_RX_HIGH_PRIO 4
#define CONFIG_BT_HOST_CRYPTO 1
#define CONFIG_BT_WHITELIST 1
#define CONFIG_BT_BUF_ACL_RX_COUNT 6
#define CONFIG_BT_BUF_ACL_TX_SIZE 69
#define CONFIG_BT_BUF_EVT_RX_COUNT 5
#define CONFIG_BT_BUF_EVT_RX_SIZE 256
#define CONFIG_BT_BUF_CMD_TX_COUNT 3
#define CONFIG_BT_BUF_CMD_TX_SIZE 256
#define CONFIG_BT_CONN_TX_MAX 3
#define CONFIG_BT_AUTO_PHY_UPDATE 1
#define CONFIG_BT_AUTO_DATA_LEN_UPDATE 1
#define CONFIG_BT_SMP 1
//#define CONFIG_BT_SMP_SC_ONLY 1
#ifdef CONFIG_BT_SMP_SC_ONLY
	#define CONFIG_BT_SMP_MIN_ENC_KEY_SIZE 16
#else
	#define CONFIG_BT_SMP_MIN_ENC_KEY_SIZE 7
#endif
#define CONFIG_BT_PRIVACY 1
#define CONFIG_BT_RPA_TIMEOUT 900
#define CONFIG_BT_SIGNING 1
#define CONFIG_BT_BONDABLE 1
#define CONFIG_BT_SMP_ENFORCE_MITM 1
#define CONFIG_BT_SMP_ALLOW_UNAUTH_OVERWRITE 1
#define CONFIG_BT_KEYS_OVERWRITE_OLDEST 1
#define CONFIG_BT_L2CAP_RX_MTU 69
#define CONFIG_BT_L2CAP_TX_BUF_COUNT 5
#define CONFIG_BT_L2CAP_TX_FRAG_COUNT 2
#define CONFIG_BT_L2CAP_TX_MTU 69
#define CONFIG_BT_RFCOMM_L2CAP_MTU 50 //FIXME
#define CONFIG_BT_L2CAP_DYNAMIC_CHANNEL 1
#define CONFIG_BT_L2CAP_ECRED 1
//#define CONFIG_BT_ATT_ENFORCE_FLOW 1
#define CONFIG_BT_ATT_PREPARE_COUNT 5
#define CONFIG_BT_ATT_TX_MAX 3
#define CONFIG_BT_GATT_SERVICE_CHANGED 1
#define CONFIG_BT_GATT_DYNAMIC_DB 1
#define CONFIG_BT_GATT_CACHING 1
#define CONFIG_BT_GATT_NOTIFY_MULTIPLE 1
#define CONFIG_BT_GATT_CLIENT 1
#define CONFIG_BT_GATT_READ_MULTIPLE 1
#define CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS 1
#define CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS 1
#define CONFIG_BT_PERIPHERAL_PREF_MIN_INT 24
#define CONFIG_BT_PERIPHERAL_PREF_MAX_INT 40
#define CONFIG_BT_PERIPHERAL_PREF_SLAVE_LATENCY 0
#define CONFIG_BT_PERIPHERAL_PREF_TIMEOUT 42
#define CONFIG_BT_DEVICE_NAME_GATT_WRITABLE 1
#define CONFIG_BT_MAX_PAIRED 1
#define CONFIG_BT_CREATE_CONN_TIMEOUT 3
#define CONFIG_BT_CONN_PARAM_UPDATE_TIMEOUT 5000
#define CONFIG_BT_BACKGROUND_SCAN_INTERVAL 2048
#define CONFIG_BT_BACKGROUND_SCAN_WINDOW 18
#define CONFIG_BT_DEVICE_NAME_DYNAMIC 1
#define CONFIG_BT_DEVICE_NAME_MAX 65
#define CONFIG_BT_DEVICE_NAME "AmbeaZ2_BT_DEV"
#define CONFIG_BT_DEVICE_APPEARANCE 833
#define CONFIG_BT_ID_MAX 1
#define CONFIG_BT_ECC 1
#define CONFIG_BT_HOST_CCM 1
#define CONFIG_BT_HCI_VS_EVT_USER 1
#define CONFIG_BT_SHELL 1
#define CONFIG_BT_COMPANY_ID 0x01D9
//#define CONFIG_BT_BREDR 1
#define CONFIG_BT_MAX_SCO_CONN 1
#define CONFIG_BT_PAGE_TIMEOUT 10000 //not sure, Casually defined 
//#define CONFIG_BT_AVDTP 1
#define CONFIG_BT_RFCOMM 1
#define CONFIG_BT_BUF_EVT_DISCARDABLE_SIZE 257
//#define CONFIG_BT_AUDIO 1
//#define CONFIG_BT_ISO 1
#ifdef CONFIG_BT_ISO
	#define CONFIG_BT_MAX_ISO_CONN 1
	#define CONFIG_BT_ISO_TX_BUF_COUNT 1
	#define CONFIG_BT_ISO_TX_FRAG_COUNT 2
	#define CONFIG_BT_ISO_TX_MTU 251
	#define CONFIG_BT_ISO_RX_BUF_COUNT 1
	#define CONFIG_BT_ISO_RX_MTU 251
	#define CONFIG_BT_AUDIO_DEBUG_ISO 1
#endif
#define CONFIG_BT_MESH 1
#ifdef CONFIG_BT_MESH
	#define CONFIG_BT_MESH_IV_UPDATE_SEQ_LIMIT 0x800000
	#define CONFIG_BT_MESH_DEBUG 1
	#define CONFIG_BT_MESH_PROV 1
	#define CONFIG_BT_MESH_PROV_DEVICE 1
	#define CONFIG_BT_MESH_PB_ADV 1
	#define CONFIG_BT_MESH_UNPROV_BEACON_INT 5
	#define CONFIG_BT_MESH_PB_ADV_RETRANS_TIMEOUT 500
	#define CONFIG_BT_MESH_PROVISIONER 1
	#define CONFIG_BT_MESH_CDB 1
	#define CONFIG_BT_MESH_CDB_NODE_COUNT 1
	#define CONFIG_BT_MESH_CDB_SUBNET_COUNT 1
	#define CONFIG_BT_MESH_CDB_APP_KEY_COUNT 1
	//#define CONFIG_BT_MESH_PROXY 1
	#define CONFIG_BT_MESH_PB_GATT 1
	//#define CONFIG_BT_MESH_GATT_PROXY 1
	//#define CONFIG_BT_MESH_GATT_PROXY_ENABLED 1
	#define CONFIG_BT_MESH_NODE_ID_TIMEOUT 60
	#define CONFIG_BT_MESH_PROXY_FILTER_SIZE 3
	#define CONFIG_BT_MESH_SUBNET_COUNT 1
	#define CONFIG_BT_MESH_APP_KEY_COUNT 1
	#define CONFIG_BT_MESH_MODEL_KEY_COUNT 1
	#define CONFIG_BT_MESH_MODEL_GROUP_COUNT 1
	#define CONFIG_BT_MESH_LABEL_COUNT 1
	#define CONFIG_BT_MESH_CRPL 10
	#define CONFIG_BT_MESH_MSG_CACHE_SIZE 10
	#define CONFIG_BT_MESH_ADV_BUF_COUNT 6
	#define CONFIG_BT_MESH_ADV_LEGACY 1
	#define CONFIG_BT_MESH_ADV_STACK_SIZE 1024
	#define CONFIG_BT_MESH_IVU_DIVIDER 4
	#define CONFIG_BT_MESH_TX_SEG_MSG_COUNT 1
	#define CONFIG_BT_MESH_RX_SEG_MSG_COUNT 1
	#define CONFIG_BT_MESH_SEG_BUFS 64
	#define CONFIG_BT_MESH_RX_SEG_MAX 3
	#define CONFIG_BT_MESH_TX_SEG_MAX 3
	#define CONFIG_BT_MESH_DEFAULT_TTL 7
	#define CONFIG_BT_MESH_LOOPBACK_BUFS 3
	#define CONFIG_BT_MESH_TX_SEG_RETRANS_COUNT 4
	#define CONFIG_BT_MESH_TX_SEG_RETRANS_TIMEOUT_UNICAST 400
	#define CONFIG_BT_MESH_TX_SEG_RETRANS_TIMEOUT_GROUP 50
	#define CONFIG_BT_MESH_NETWORK_TRANSMIT_COUNT 2
	#define CONFIG_BT_MESH_NETWORK_TRANSMIT_INTERVAL 20
	#define CONFIG_BT_MESH_RELAY 1
	#define CONFIG_BT_MESH_RELAY_ENABLED 1
	#define CONFIG_BT_MESH_RELAY_RETRANSMIT_COUNT 2
	#define CONFIG_BT_MESH_RELAY_RETRANSMIT_INTERVAL 20
	#define CONFIG_BT_MESH_BEACON_ENABLED 1
	#define CONFIG_BT_MESH_LOW_POWER 1
	#define CONFIG_BT_MESH_LPN_ESTABLISHMENT 1
	#define CONFIG_BT_MESH_LPN_AUTO 1
	#define CONFIG_BT_MESH_LPN_AUTO_TIMEOUT 15
	#define CONFIG_BT_MESH_LPN_RETRY_TIMEOUT 8
	#define CONFIG_BT_MESH_LPN_RSSI_FACTOR 0
	#define CONFIG_BT_MESH_LPN_RECV_WIN_FACTOR 0
	#define CONFIG_BT_MESH_LPN_MIN_QUEUE_SIZE 1
	#define CONFIG_BT_MESH_LPN_RECV_DELAY 100
	#define CONFIG_BT_MESH_LPN_POLL_TIMEOUT 300
	#define CONFIG_BT_MESH_LPN_INIT_POLL_TIMEOUT 300
	#define CONFIG_BT_MESH_LPN_SCAN_LATENCY 10
	#define CONFIG_BT_MESH_LPN_GROUPS 8
	#define CONFIG_BT_MESH_FRIEND 1
	#define CONFIG_BT_MESH_FRIEND_ENABLED 1
	#define CONFIG_BT_MESH_FRIEND_RECV_WIN 255
	#define CONFIG_BT_MESH_FRIEND_QUEUE_SIZE 16
	#define CONFIG_BT_MESH_FRIEND_SUB_LIST_SIZE 3
	#define CONFIG_BT_MESH_FRIEND_LPN_COUNT 2
	#define CONFIG_BT_MESH_FRIEND_SEG_RX 1
	#define CONFIG_BT_MESH_CFG_CLI 1
	#define CONFIG_BT_MESH_HEALTH_CLI 1
	#define CONFIG_BT_MESH_SHELL 1
	#define CONFIG_BT_MESH_MODEL_EXTENSIONS 1
	#define CONFIG_BT_MESH_STORE_TIMEOUT 2
	#define CONFIG_BT_MESH_RPL_STORE_TIMEOUT 5
	#define CONFIG_BT_MESH_SEQ_STORE_RATE 128
#endif


/* BT Debug & Log About */
#define CONFIG_BT_ASSERT 1
#define CONFIG_BT_ASSERT_VERBOSE 1
#define CONFIG_BT_ASSERT_PANIC 1
#define CONFIG_BT_LOG_LEVEL_INF 1
#define CONFIG_BT_LOG_LEVEL 5
#define CONFIG_BT_BAS_LOG_LEVEL 0
#define CONFIG_BT_HRS_LOG_LEVEL 0
#define CONFIG_BT_TPS_LOG_LEVEL 3
#define CONFIG_BT_DEBUG 1
//#define CONFIG_BT_DEBUG_CONN 1


/* BT Monitor About */
//#define CONFIG_BT_DEBUG_MONITOR 1
#define CONFIG_BT_MONITOR_ON_DEV_NAME "UART_1"
//#define CONFIG_UART_CONSOLE_ON_DEV_NAME "UART_1"
//#define CONFIG_HAS_DTS 1
//#define CONFIG_UART_CONSOLE 1


/* BT Shell About (TBD) */


/* BT Setting About */
//#define CONFIG_SETTINGS 1
#ifdef CONFIG_SETTINGS
	#define CONFIG_BT_SETTINGS 1
	#define CONFIG_BT_SETTINGS_CCC_LAZY_LOADING 1
	#define CONFIG_BT_SETTINGS_USE_PRINTK 1
	#define CONFIG_SETTINGS_LOG_LEVEL_INF 1
	#define CONFIG_SETTINGS_LOG_LEVEL 3
	#define CONFIG_SETTINGS_DYNAMIC_HANDLERS 1
	//#define CONFIG_SETTINGS_NVS 1
	//#define CONFIG_SETTINGS_NVS_SECTOR_SIZE_MULT 1
	//#define CONFIG_SETTINGS_NVS_SECTOR_COUNT 8
#endif


/* BT Tester About (TBD) */


/* Useless, just for compatible */
#define CONFIG_KERNEL_INIT_PRIORITY_DEFAULT 40
#define CONFIG_KERNEL_INIT_PRIORITY_DEVICE 50
#define CONFIG_APPLICATION_INIT_PRIORITY 90
//#define CONFIG_TEST 1
//#define CONFIG_UART_RING_BUFFER 1
//#define CONFIG_UART_INTERRUPT_DRIVEN 1

#endif
